export const breeds = [
  "Akita Inu",
  "Alaskan Malamute",
  "Australian Shepherd",
  "Beagle",
  "Border Collie",
  "Boxer",
  "Bulldog Francés",
  "Bulldog Inglés",
  "Cane Corso",
  "Chihuahua",
  "Cocker Spaniel",
  "Doberman",
  "Golden Retriever",
  "Labrador Retriever",
  "Mastín Español",
  "Pastor Alemán",
  "Pastor Belga Malinois",
  "Pomerania",
  "Rottweiler",
  "Samoyedo",
  "Shiba Inu",
  "Siberian Husky",
  "Teckel",
  "Yorkshire Terrier"
];
