module.exports = {
  "Golden Retriever": { risk: 3, group: "Retriever" },
  "Labrador Retriever": { risk: 3, group: "Retriever" },
  "Pastor Alemán": { risk: 5, group: "Pastor" },
  "Border Collie": { risk: 2, group: "Pastor" },
  "Caniche": { risk: 2, group: "Compañía" },
  "Bulldog Francés": { risk: 8, group: "Braquicéfalo" },
  "Bulldog Inglés": { risk: 9, group: "Braquicéfalo" },
  "Pug": { risk: 9, group: "Braquicéfalo" },
  "Doberman": { risk: 6, group: "Trabajo" },
  "Rottweiler": { risk: 6, group: "Trabajo" },
  "Boxer": { risk: 7, group: "Trabajo" },
  "Beagle": { risk: 4, group: "Sabueso" },
  "Cocker Spaniel": { risk: 4, group: "Spaniel" },
  "Setter Inglés": { risk: 3, group: "Setter" },
  "Teckel": { risk: 6, group: "Sabueso" },
  "Husky Siberiano": { risk: 4, group: "Nórdico" },
  "Alaskan Malamute": { risk: 5, group: "Nórdico" },
  "Chihuahua": { risk: 5, group: "Compañía" },
  "Shih Tzu": { risk: 6, group: "Braquicéfalo" },
  "Mastín Español": { risk: 6, group: "Moloso" },
  "Dogo Argentino": { risk: 6, group: "Moloso" },
  "Akita Inu": { risk: 5, group: "Spitz" },
  "Samoyedo": { risk: 4, group: "Spitz" },
  "Bichón Maltés": { risk: 3, group: "Compañía" },
  "Yorkshire Terrier": { risk: 4, group: "Terrier" },
  "Jack Russell Terrier": { risk: 3, group: "Terrier" },
  "Whippet": { risk: 3, group: "Lebrel" },
  "Galgo Español": { risk: 2, group: "Lebrel" },
  "Basenji": { risk: 4, group: "Primitivo" },
  "Shar Pei": { risk: 8, group: "Moloso" },
  "Cane Corso": { risk: 6, group: "Moloso" },
  "American Staffordshire": { risk: 6, group: "Terrier" },
  "Bull Terrier": { risk: 7, group: "Terrier" },
  "Papillon": { risk: 3, group: "Compañía" },
  "Pomerania": { risk: 5, group: "Spitz" },
  "San Bernardo": { risk: 7, group: "Moloso" },
  "Gran Danés": { risk: 7, group: "Moloso" },
  "Weimaraner": { risk: 4, group: "Caza" },
  "Braco Alemán": { risk: 4, group: "Caza" },
  "Pointer Inglés": { risk: 3, group: "Caza" },
  "Basset Hound": { risk: 6, group: "Sabueso" },
  "Collie": { risk: 3, group: "Pastor" },
  "Pastor Australiano": { risk: 3, group: "Pastor" },
  "Pastor Belga": { risk: 4, group: "Pastor" },
  "Malinois": { risk: 5, group: "Pastor" }
};
